### ISSUE TITLE
not possible to connect to elastic

### ISSUE THREAD

**Issue by UweW** [ThorbenJ/nrc-elasticsearch-nodes#1]
Hi,
it is not possible to connect to the elastic node.
Always getting "ConnectionError: unable to verify the first certificate"
Is it possible to disable cert validation ?

best regards
UWe

**Comment by ThorbenJ** [comment]
In the Advanced Options box you can pass any argument accepted by Elasticsearch-js new Client() constructor: https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/client-connecting.html

Not tested but reading https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/client-connecting.html#auth-tls you should be able to use:
```
tls: 
  // might be required if it's a self-signed certificate
  rejectUnauthorized: false
```

![image](https://user-images.githubusercontent.com/1284751/224564879-0634d36b-2795-4b62-b472-b8f3b56e9faa.png)

**Comment by UweW** [comment]
Hi,
without the comment in line 2 it works. 
Thanks a lot.

Uwe

**Comment by ThorbenJ** [comment]
I guess the comment is not valid yaml, I should have been more careful with my copy/pasting.
Glad it worked.

**Comment by sjlongland** [comment]
> I guess the comment is not valid yaml, I should have been more careful with my copy/pasting. Glad it worked.

Comments in YAML follow Unix shell conventions:

```yaml
tls: 
  # might be required if it's a self-signed certificate
  rejectUnauthorized: false
```
