### ISSUE TITLE
i can't find es connection node

### ISSUE THREAD

**Issue by estoylive** [ThorbenJ/nrc-elasticsearch-nodes#2]
i can see it is enabled, but I can't figure out how to load this node. Why?  i am new with nodered so I may have the solution in my face and not seeing it, sorry if that is the case XD

Can you tell me how or where I should set my API credentials for elastic search cloud?

**Comment by ThorbenJ** [comment]
Hi. Configuration nodes are a core feature of NodeRed. I had a quick look and I hope this part of the user documentation will help you: https://nodered.org/docs/user-guide/concepts#config-node, there are two further links on working with config nodes in nodered that also include UI screen shots.

Also where you select connection in the configuration of any elasticsearch node, there is a button to create a new es connection configuration node. Once you've created it, all other elasticsearch "action" nodes can use it. Just select it in their config.
